version: 2
jobs:
  test:
    docker:
      - image: cypress/base:10
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: $(npm bin)/commit-message-install --else "npm i cypress"
      - run: npm run cy:verify
      - save_cache:
          key: cache-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - run: node index.js
      - run: node async.js
      - run: npm test

workflows:
  version: 2
  build:
    jobs:
      - test

# machine:
#   node:
#     version: 8

# test:
#   override:
#     - $(npm bin)/commit-message-install --else "npm i cypress"
#     - $(npm bin)/cypress verify
#     - node index.js
#     - node async.js
#     - npm test
